# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cf39a77399ef1afcf06988c7b06de1d666dfa772b334ea49a1eb821411da00066de267de98071d3a6bd0ff371c8c3ba5a78cabfc7715533bb8bf74ca6b73aef3

test:
  secret_key_base: 71f54c3c5fa43b938df060d1e7e34a1d968c53f77b9bf57e05fd2410317820edbdab6ddfc9912c4ccabe0963d4a2d81c3166d1101e794a37107a7952acf1eb0b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
