# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8ad116b6c6aa3794be30923450d7904b5426665958485958af6470ad39806897bc75d9ddfe531ec709e3eabb9e82b170cd7f46b9dea07711f18af2b41aeee968

test:
  secret_key_base: 1417ecba048fb6370cc5d9e0b18893419c1621646f988de06ccd6b1e800b5d866a3adfb9fc41eeb7ef893e2abcc27db68c43604e768eb3fdac3f67c1c9bbd0c7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
